[tool.commitizen]
name = "cz_conventional_commits"
version = "0.3.0"
tag_format = "v$version"
version_files = ["index.html:APP_VERSION"]
update_changelog_on_bump = true
changelog_incremental = true
changelog_file = "CHANGELOG.md"
major_version_zero = true
